export const apiUrls = {
  applyBaseUrl: process.env.NEXT_PUBLIC_APPLY_BACKEND_API,
  academicBaseUrl: process.env.NEXT_PUBLIC_ACADEMIC_BACKEND_API,
  financeBaseUrl: process.env.NEXT_PUBLIC_FINANCE_BACKEND_API,
  commonBaseUrl: process.env.NEXT_PUBLIC_COMMON_BACKEND_API,
  userManagementBaseUrl: process.env.NEXT_PUBLIC_USER_MANAGEMENT_BACKEND_API,
  enrolmentBaseUrl: process.env.NEXT_PUBLIC_ENROLMENT_BACKEND_API,
  documentBaseURl: process.env.NEXT_PUBLIC_DOCUMENT_BACKEND_API,
};

export const apiEndPoint = {
  loadMasterData: "apply/master/loadMasterData ",
  register: "auth/apply/register",
  verifyOtp: "auth/apply/verify-otp",
  refreshToken: "auth/refresh-token",
  salesAgent: "user-management/user/role/Sales",
  application: "application",
  programs: "academics/programs/all",
  commonDocuments: "document-type",
  document: "document",
  applicationDetails: "apply/lead/:leadId/application/:applicationCode",
  enrolmentApplicationDetails: "admissions/:applicationCode",
  studentProgram: "finance/programs-fee/byProgramCode/:programCode",
  stateDetails: "state/:countryCode",
  nationalityStatus: "nationality-status",
  identificationType: "identification-Type",
  lead: "apply/lead",
  payu: "/payment/payu",
  termAndCondFile: "apply/application/terms-condition/:name/:email",
  checkDuplicateEmail: "apply/lead/check-duplicate-email/:email/leadId/:leadId",
  draft: "apply/draft",
  declarationForm: "download/declarationForm",
  GETCURRENCYCONVERSION: "finance/programs-fee/fee-conversion-rate/",
  studyModes: "study-mode",
  program: "academics/programs/:programCode",
  programRmat: "academics/rmat/byProgramCode/:programCode",
  rmat: "application/rmat/details/:studentCode",
  ukhesheToken: "finance/payments/get-ukheshe-token",
  updatePayment: "finance/payments/ukheshe-payment",
  bursary: "bursary",
  student: "student",
  status: "set-status",
  checkDuplicateIdNumber:
    "apply/lead/check-duplicate-id-number/:idNumber/leadId/:leadId",
  updateDocumentStatus: "document/:documentCode/active",
  documentCode: "next-code/DOC",
  documentRemove: "document/documentCode",
  updateCredit: "credit-history",
};
