export const apiUrls = {
  baseApiURL: process.env.NEXT_PUBLIC_BASE_URL
};

export const apiEndPoint = {
  loadMasterData: "master/loadMasterData ",
  register: "auth/apply/register",
  verifyOtp: "auth/apply/verify-otp",
  refreshToken: "auth/refresh-token",
  salesAgent: "user/role/Sales",
  application: "application",
  programs: "programs/all",
  commonDocuments: "document-type",
  document: "document",
  applicationDetails: "lead/:leadId/application/:applicationCode",
  enrolmentApplicationDetails: "admissions/:applicationCode",
  studentProgram: "programs-fee/byProgramCode/:programCode",
  stateDetails: "state/:countryCode",
  nationalityStatus: "nationality-status",
  identificationType: "identification-Type",
  lead: "lead",
  payu: "/payment/payu",
  termAndCondFile: "application/terms-condition/:name/:email",
  checkDuplicateEmail: "lead/check-duplicate-email/:email/leadId/:leadId",
  draft: "draft",
  declarationForm: "download/declarationForm",
  GETCURRENCYCONVERSION: "programs-fee/fee-conversion-rate/",
  studyModes: "study-mode",
  program: "programs/:programCode",
  programRmat: "rmat/byProgramCode/:programCode",
  rmat: "application/rmat/details/:studentCode",
  ukhesheToken: "payments/get-ukheshe-token",
  updatePayment: "payments/ukheshe-payment",
  bursary: "bursary",
  student: "student",
  status: "set-status",
  checkDuplicateIdNumber:
    "lead/check-duplicate-id-number/:idNumber/leadId/:leadId",
  updateDocumentStatus: "document/:documentCode/active",
  documentCode: "next-code/DOC",
  documentRemove: "document/documentCode",
  updateCredit: "credit-history",
};
