export const mbaDocs = ["MOTIVATIONLETTER", "INTERVIEWNOTES"];

export const docType = {
  IDPASSPORT: "IDPASSPORT",

  RESUMECV: "RESUMECV",

  MATRIC: "MATRIC",

  HIGHESTQUALIFICATION: "HIGHESTQUALIFICATION",

  BURSARYLETTER: "BURSARYLETTER",

  DECLARATIONFORM: "DECLARATIONFORM",

  MOTIVATIONLETTER: "MOTIVATIONLETTER",

  INTERVIEWNOTES: "INTERVIEWNOTES",
};
